package myjsp;
import java.io.Serializable;

import java.io.IOException;
import java.io.PrintWriter;

import jakarta.servlet.GenericServlet;
import jakarta.servlet.ServletException;
import jakarta.servlet.ServletRequest;
import jakarta.servlet.ServletResponse;
import jakarta.servlet.annotation.WebServlet;
@WebServlet("/form")
public class MyServlet3 extends GenericServlet {

	@Override
	public void service(ServletRequest req, ServletResponse res) throws ServletException, IOException {
	
		String respons="<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"UTF-8\">\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "    <title>Employee Registration Form</title>\r\n"
				+ "    <style>\r\n"
				+ "        /* Basic styling */\r\n"
				+ "        body {\r\n"
				+ "            font-family: Arial, sans-serif;\r\n"
				+ "            background-color: #f4f4f4;\r\n"
				+ "            display: flex;\r\n"
				+ "            justify-content: center;\r\n"
				+ "            align-items: center;\r\n"
				+ "            height: 100vh;\r\n"
				+ "            margin: 0;\r\n"
				+ "        }\r\n"
				+ "        .container {\r\n"
				+ "            max-width: 500px;\r\n"
				+ "            width: 90%;\r\n"
				+ "            background: white;\r\n"
				+ "            padding: 20px;\r\n"
				+ "            border-radius: 10px;\r\n"
				+ "            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n"
				+ "        }\r\n"
				+ "        h2 {\r\n"
				+ "            text-align: center;\r\n"
				+ "            color: #333;\r\n"
				+ "        }\r\n"
				+ "        .form-group {\r\n"
				+ "            margin-bottom: 15px;\r\n"
				+ "        }\r\n"
				+ "        label {\r\n"
				+ "            font-weight: bold;\r\n"
				+ "            display: block;\r\n"
				+ "            margin-bottom: 5px;\r\n"
				+ "        }\r\n"
				+ "        input, select {\r\n"
				+ "            width: 100%;\r\n"
				+ "            padding: 10px;\r\n"
				+ "            border: 1px solid #ccc;\r\n"
				+ "            border-radius: 5px;\r\n"
				+ "            font-size: 16px;\r\n"
				+ "        }\r\n"
				+ "        button {\r\n"
				+ "            width: 100%;\r\n"
				+ "            background: #28a745;\r\n"
				+ "            color: white;\r\n"
				+ "            padding: 10px;\r\n"
				+ "            border: none;\r\n"
				+ "            border-radius: 5px;\r\n"
				+ "            font-size: 18px;\r\n"
				+ "            cursor: pointer;\r\n"
				+ "        }\r\n"
				+ "        button:hover {\r\n"
				+ "            background: #218838;\r\n"
				+ "        }\r\n"
				+ "        /* Responsive Design */\r\n"
				+ "        @media (max-width: 600px) {\r\n"
				+ "            .container {\r\n"
				+ "                width: 95%;\r\n"
				+ "            }\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "    <div class=\"container\">\r\n"
				+ "        <h2>Employee Registration</h2>\r\n"
				+ "        <form action=\"LoginServlet\" method=\"post\">\r\n"
				+ "            <div class=\"form-group\">\r\n"
				+ "                <label for=\"id\">Employee ID:</label>\r\n"
				+ "                <input type=\"number\" id=\"id\" name=\"id\" required>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"form-group\">\r\n"
				+ "                <label for=\"name\">Full Name:</label>\r\n"
				+ "                <input type=\"text\" id=\"name\" name=\"name\" required>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"form-group\">\r\n"
				+ "                <label for=\"joiningDate\">Joining Date:</label>\r\n"
				+ "                <input type=\"date\" id=\"joiningDate\" name=\"joiningDate\" required>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"form-group\">\r\n"
				+ "                <label for=\"salary\">Salary:</label>\r\n"
				+ "                <input type=\"number\" id=\"salary\" name=\"salary\" step=\"0.01\" required>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"form-group\">\r\n"
				+ "                <label for=\"email\">Email:</label>\r\n"
				+ "                <input type=\"email\" id=\"email\" name=\"email\" required>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"form-group\">\r\n"
				+ "                <label for=\"phoneNumber\">Phone Number:</label>\r\n"
				+ "                <input type=\"tel\" id=\"phoneNumber\" name=\"phoneNumber\" pattern=\"[0-9]{10}\" required>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"form-group\">\r\n"
				+ "                <label for=\"role\">Role:</label>\r\n"
				+ "                <select id=\"role\" name=\"role\" required>\r\n"
				+ "                    <option value=\"Manager\">Manager</option>\r\n"
				+ "                    <option value=\"Developer\">Developer</option>\r\n"
				+ "                    <option value=\"Tester\">Tester</option>\r\n"
				+ "                    <option value=\"HR\">HR</option>\r\n"
				+ "                    <option value=\"Other\">Other</option>\r\n"
				+ "                </select>\r\n"
				+ "            </div>\r\n"
				+ "            <button type=\"submit\">Register</button>\r\n"
				+ "        </form>\r\n"
				+ "    </div>\r\n"
				+ "</body>\r\n"
				+ "</html>\r\n"
				+ "";
		PrintWriter writer = res.getWriter();
		writer.println(respons);
	}

}
